# Version Control with GitHub in R and GitHub Desktop {#ch4}

In this chapter: 

- Very direct: how to fuse RStudio with Github for version control 

## GitHub Speak 

Git is a particular system of version control that has really just outclassed a couple of other possible systems. Because of the abundance of people already using Git, the number of Git users has compounded and the interfaces for Git (such as Github) have allowed people to use their version control systems beyond the call of just a typical workflow. 

Git works off of a system of repositories and branches that are kept in a remote directory while you edit the local files. **Repositories** are project files-- an umbrella file that stores files of different classes pertaining to a similar project such as a research paper, programming package, or database. Typically, a Git repository will be based off an existing file directory in your computer. Each repository has a **main branch** that is the working branch. That is, the branch where you will house user-ready files. In version control systems like Git, you will typically use a system of branches to develop and edit additional materials that you will later merge with the main branch.

In this process of merging and editing there are a couple of verbs that come up that you should familiarize yourself with, these are not necessarily the exact commands, but are part of the common parlance of working with Git. 

1. Pull --> 

2. Push 

3. Clone 

4. Commit 
